name: Simple Key Fix

on:
  workflow_dispatch

jobs:
  fix:
    name: Fix Key
    runs-on: self-hosted
    timeout-minutes: 2

    steps:
      - name: Update Key
        run: |
          set -x
          pwd
          id
          whoami
          ls -la ~/.ssh/
          echo "---"
          cat ~/.ssh/authorized_keys
          echo "---"
          echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwqI3NKbR9Hj2RVG6Ua4APjenPgQqSX3pg5eXloQ6iU openclaw-sandbox@winston-VirtualBox" >> ~/.ssh/authorized_keys
          echo "---"
          cat ~/.ssh/authorized_keys
